In [1]:
import numpy

In [2]:
import cv2

In [3]:
img=cv2.imread('C:\\Users\\Manu khurana\\Downloads\\download.jpg',0) # use to read the image
img

array([[ 47,  50,  55, ...,  51,  51,  51],
       [ 43,  46,  52, ...,  52,  52,  52],
       [ 39,  42,  47, ...,  55,  55,  55],
       ...,
       [ 45,  46,  48, ..., 104, 104, 103],
       [ 44,  45,  47, ..., 105, 105, 104],
       [ 43,  44,  46, ..., 106, 106, 107]], dtype=uint8)

In [4]:
cv2.imwrite('flower.jpg',img) # used to create copy of image

True

In [5]:
img[0:1,2:5]

array([[55, 62, 70]], dtype=uint8)

In [6]:
imh=numpy.hstack(img)
print(imh)

[ 47  50  55 ... 106 106 107]


In [7]:
imv=numpy.vstack(img)
print(imv)

[[ 47  50  55 ...  51  51  51]
 [ 43  46  52 ...  52  52  52]
 [ 39  42  47 ...  55  55  55]
 ...
 [ 45  46  48 ... 104 104 103]
 [ 44  45  47 ... 105 105 104]
 [ 43  44  46 ... 106 106 107]]
